[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=xdg-shell,LD_PRELOAD=/usr/lib/libtls-padding.so,KWIN_DRM_USE_MODIFIERS=0,KWIN_DRM_NO_AMS=1,KWIN_COMPOSE=O2ES,GBM_BACKEND=hybris,__GLX_VENDOR_LIBRARY_NAME=libhybris

InputMethod=

[Wayland]
CompositorCommand=kwin_wayland --no-global-shortcuts --no-lockscreen --inputmethod maliit-keyboard --locale1
